Repository trustoverip/TechArch, pull requests merged in 2022-11, with the labels that each got.

#49 governance files: CODEOWNERS, CONTRIBUTING.md, and GOVERNANCE.md
  CODEOWNERS
  CONTRIBUTING.md
  GOVERNANCE.md
Labels: priority: high, status: last-call, type: admin

#11 Ack addtnl form of interop that's important: with legacy tech
  spec.md
Labels: status: unassigned, type: content, status: needs-review

#58 updated PR notes
  CONTRIBUTING.md
Labels: priority: low, type: admin

#59 Section 3 adjust wording to interop principle
  spec.md
Labels: priority: high, status: last-call, type: editorial

#54 Update section 6.1 wrt "authenticity"
  spec.md
Labels: priority: high, status: last-call, type: content

#61 Initial updates to the editors section.
  spec.md
Labels: priority: medium, type: editorial, status: needs-review

#62 Clarify Endpoint System's locus of control
  spec.md
Labels: priority: high, type: editorial, status: needs-review
